### ISSUE TITLE
Hardcoded certs in the ComponentTests Suite have expired

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/statsd-injector-release#46]
### Problem
`metronCrt`, `statsdCrt`, and `caCert` hardcoded in `component_tests/certificates_test.go` have expired ([link](https://github.com/cloudfoundry/statsd-injector-release/blob/main/src/component_tests/certificates_test.go#L45-L191)).

This is causing the ComponentTests Suite to continuously fail.

### Solution

**Option 1 (Easy)**
Update the variables. Set them to new, non-expired certs.

**Option 2 (Harder?)**
Add code or a new module import to generate the certs prior to the test run so that we don't have to hardcode them anymore.

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry/statsd-injector-release/pull/47
