### ISSUE TITLE
Statsd deployment name is broken

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/statsd-injector-release#5]
So a few days ago one of our monitoring dashboards stopped working. Rather than the usual deployment name of `cf`, the deployment name was now `p("statsd_injector.deployment").empty? ? spec.deployment : p("statsd_injector.deployment")`. Interesting, we thought. Turns out the `<%= ... %>` that were removed [here](https://github.com/cloudfoundry/statsd-injector-release/commit/b581d3065783aa8e44d0c7eb9ac5d0d6fbdbebc3) were kinda important : )

Looks like there's also PR #4 that does the right thing as well.

**Comment by markikollasch** [comment]
Thanks for the heads-up. We'll take a look at it.
