### ISSUE TITLE
"fixtures" and "_fixtures" directories

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/statsd-injector-release#7]
Hi,
my team would like to use statsd-injector-release-v1.2.0 and to approve that I've to analyze it's source code and the code of its dependencies chain, to be sure that they don't have problematic licenses.

Now some code and dependencies come from directories "fixtures" and "_fixtures".

Could you please tell me if what is valid for the buildpacks and specified at:
cloudfoundry/binary-buildpack#21
is also applicable to statsd-injector-release-v1.2.0?

Thank for your help.

**Comment by bradylove** [comment]
Similar to github.com/cloudfoundry/loggregator-release/issues/375.

**Comment by luisapace** [comment]
Thanks Brady.
